services:
  bluetooth-receiver:
    image: pinkynrg/bluetooth-receiver:latest
    container_name: bluetooth-receiver
    network_mode: host
    privileged: true
    volumes:
      - /lib/modules:/lib/modules:ro
      - bluetooth-data:/var/lib/bluetooth
    environment:
      - DEVICE_NAME=Snapcast Receiver
    restart: always

volumes:
  bluetooth-data:
